export const janet_craig = {
    Appeal: "Robustness",
    Avaibility: "Regular",
    "Available sizes (Pot)": "4in to 14in / 10cm to 36cm",
    Bearing: "Erect",
    "Blooming season": "Winter / Spring",
    Categories: "Dracaena",
    Climat: "Tropical",
    "Color of blooms": "Light green",
    "Color of leaf": [ "Dark green" ],
    "Common name": [ "Janet Craig" ],
    "Common name (fr.)": "Janet Craig",
    Description: null,
    Disease: "N/A",
    Family: "Liliaceae",
    Growth: "Regular",
    "Height at purchase": { M: 0.91, CM: 91 },
    "Height potential": { M: 3.66, CM: 366 },
    Img: "http://www.tropicopia.com/house-plant/thumbnails/5556.jpg",
    Insects: [ "Mealy bug", "Scale" ],
    "Latin name": "Dracaena deremensis 'Janet Craig'",
    "Light ideal": "Strong light ( 21,500 to 3,200 lux/2000 to 300 fc)",
    "Light tolered": "Diffuse light ( Less than 5,300 lux / 500 fc)",
    Origin: [ "Cultivar" ],
    "Other names": null,
    Perfume: null,
    "Pot diameter (cm)": { M: 0.25, CM: 25 },
    Pruning: "If needed",
    Style: "Bush",
    "Temperature max": { F: 86, C: 30 },
    "Temperature min": { F: 50, C: 10 },
    Url: "http://www.tropicopia.com/house-plant/detail.np/detail-121.html",
    Use: [ "Potted plant", "Secondary" ],
    Watering: "Keep moist between watering & Can dry between watering",
    "Width at purchase": { M: 0.91, CM: 91 },
    "Width potential": { M: 1.22, CM: 122 },
    Zone: [ "11-10" ],
    id: "53417c12-4824-5995-bce0-b81984ebbd1d"
}